name: bug_localisation
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip=21.0
  - pytorch
  - torchaudio
  - torchvision
  - cudatoolkit=11.4
  - pandas
  - numpy
  - pip:
    - scipy
    - tqdm
    - sentence-transformers
    - matplotlib
